import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {prepare} from '../scripts/whatsapp-review-prepare.mjs';import {createAdapter,sourceFingerprint,validateExecutionApproval,verifyDeploymentSurface} from '../scripts/whatsapp-review-cli.mjs';import {CONTRACT,sha256} from '../scripts/whatsapp-review-runner.mjs';
function setup(t){const dir=mkdtempSync(join(tmpdir(),'review-cli-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const now=Date.now()+60000,base={name:CONTRACT.worker,compatibility_date:'2024-11-01',routes:[{pattern:'find-staging.edenmish.com',custom_domain:true},{pattern:'ops-staging.edenmish.com',custom_domain:true}],d1_databases:[{binding:'DB',database_name:'edenmish-staging',database_id:CONTRACT.database}],vars:{BOOKING_URL:'https://staging.edenmish.com'}};prepare({base,plan:{recipient:'+972500000001',startsAt:now,endsAt:now+900000},directory:dir});const a=JSON.parse(readFileSync(join(dir,'approval.json')));Object.assign(a,{approved:true,approvedAt:Date.now()-1000,approvalExpiresAt:now+3600000,feesBounded:true,maxAdditionalMandatoryFeeMicros:780000,feeEvidence:'synthetic',priorHistorySha256:sha256(JSON.stringify(Array.from({length:14},()=>[])))});let vars=JSON.parse(readFileSync(a.configPath)).vars,key=false,afterDeploy=null,afterFinalRead=null,stopped=null,alive=true;const calls=[];
 for(const [i,kind] of ['primary','watchdog'].entries())writeFileSync(join(dir,kind+'.json'),JSON.stringify({kind,at:Date.now(),endsAt:a.endsAt,pid:90000+i,sourceSha256:a.sourceSha256,grantId:CONTRACT.grantId}),{mode:0o600});
 const command=async(file,args,options)=>{calls.push({args:[...args],input:options.input?'present':null});let value;
  if(args.includes('deployments'))value=[{created_on:'2026-10-10',versions:[{version_id:'synthetic-version',percentage:100}]}];
  else if(args.includes('versions'))value={id:'synthetic-version',resources:{bindings:[...Object.entries(vars).map(([name,text])=>({name,type:'plain_text',text})),{name:'DB',type:'d1',id:CONTRACT.database},...(key?[{name:'WHATSAPP_BOOKING_OPENAI_API_KEY',type:'secret_text'}]:[])]}};
  else if(args.includes('secret')){if(args.includes('delete'))key=false;else if(args.includes('put')){assert.ok(options.input.startsWith('sk-synthetic'));key=true;}value=true;}
  else if(args.includes('deploy')){vars=JSON.parse(readFileSync(args[args.indexOf('--config')+1])).vars;if(afterDeploy)afterDeploy();value=true;}
  else {const sql=args[args.indexOf('--command')+1]||'';
   if(sql.startsWith('SELECT * FROM whatsapp_pilot_budgets'))value=Array.from({length:14},()=>({success:true,results:[]}));
   else if(sql.startsWith('SELECT status,source_sha256'))value=[{success:true,results:[{status:'matched',source_sha256:a.sourceSha256,expires_at:a.endsAt+1}]}];
   else if(sql.startsWith('SELECT stopped_reason,starts_at')){value=[{success:true,results:[{stopped_reason:stopped,starts_at:a.startsAt,expires_at:a.endsAt}]}];if(afterFinalRead)afterFinalRead();}
   else if(sql.startsWith('SELECT * FROM whatsapp_continuation_review_grants'))value=[{success:true,results:[{id:CONTRACT.grantId,version:6,starts_at:a.startsAt,expires_at:a.endsAt,stopped_reason:null,lock_id:null,spent_micros:0,model_micros:0,inbound:0,outbound:0,address:0,model:0}]},{success:true,results:[{status:'matched',source_sha256:a.sourceSha256,expires_at:a.endsAt+1}]}];
   else value=[{success:true,results:[],meta:{changes:1}}];
  }return {stdout:JSON.stringify(value),stderr:''};};
 return {a,dir,calls,io:createAdapter(a,sourceFingerprint(),{command,isAlive:()=>{if(!alive)throw Error('dead');},fetchImpl:()=>{throw Error('no provider');}}),setKey:v=>key=v,setAfterDeploy:fn=>afterDeploy=fn,setAfterFinalRead:fn=>afterFinalRead=fn,stop:()=>stopped='operator_stop',dead:()=>alive=false};}
test('offline preparation is OFF/unapproved, exclusive and private; no real identities',t=>{const h=setup(t),a=JSON.parse(readFileSync(join(h.dir,'approval.json')));assert.equal(a.approved,false);assert.equal(a.feesBounded,false);assert.equal(JSON.parse(readFileSync(a.configPath)).vars.WHATSAPP_BOOKING_ENABLED,'off');assert.equal(JSON.parse(readFileSync(a.cleanupConfigPath)).vars.WHATSAPP_BOOKING_CONTINUATION_END,'');assert.equal(h.calls.length,0);});
test('CLI checks metadata, durable proof INSERT, and settled proof without message body reads',async t=>{const h=setup(t);await h.io.assertOff();assert.equal(await h.io.reserve({id:CONTRACT.id,reserved_micros:56320}),true);assert.equal(await h.io.finish({status:'matched',finished_at:Date.now()}),true);assert.ok(h.calls.some(c=>c.args.some(a=>a.startsWith('INSERT INTO whatsapp_review_preflight'))));assert.ok(!JSON.stringify(h.calls).includes('state_json'));});
test('cleanup is idempotent, stops ledger first, pins OFF config, removes only named temporary key',async t=>{const h=setup(t);h.setKey(true);for(let i=0;i<2;i++){const r=await h.io.cleanup('operator_stop');assert.equal(r.grantStopped,true);assert.equal(r.flagsOff,true);assert.equal(r.keyAbsent,true);assert.equal(r.callbackVerified,false);}assert.ok(h.calls[0].args.some(a=>a.startsWith('UPDATE whatsapp_continuation_review_grants')));const deletions=h.calls.filter(c=>c.args.includes('delete'));assert.equal(deletions.length,1);assert.ok(deletions[0].args.includes('WHATSAPP_BOOKING_OPENAI_API_KEY'));});
test('cleanup config drift cannot deploy changed bundle; stop/key cleanup still attempted',async t=>{const h=setup(t);h.setKey(true);writeFileSync(h.a.cleanupConfigPath,readFileSync(h.a.cleanupConfigPath)+' ');const r=await h.io.cleanup('stop');assert.equal(r.grantStopped,true);assert.equal(r.keyAbsent,true);assert.equal(r.flagsOff,false);assert.equal(h.calls.filter(c=>c.args.includes('deploy')).length,0);});
test('temporary key install requires proof/OFF and passes only stdin',async t=>{const h=setup(t);await h.io.installKey('sk-synthetic-only-key');const put=h.calls.find(c=>c.args.includes('put'));assert.equal(put.input,'present');assert.ok(!JSON.stringify(put.args).includes('sk-synthetic'));});
test('activation refuses absent supervisor heartbeat before deploy',async t=>{const h=setup(t);h.setKey(true);rmSync(join(h.dir,'primary.json'));await assert.rejects(()=>h.io.activate());assert.equal(h.calls.filter(c=>c.args.includes('deploy')).length,0);});
test('hidden key helper refuses getpass echo fallback before reading input',()=>{const helper=new URL('../scripts/whatsapp-review-key-entry.py',import.meta.url).pathname;const code="import runpy,sys,getpass,warnings\ndef bad(prompt):\n warnings.warn('no terminal',getpass.GetPassWarning)\n raise AssertionError('must not read')\ngetpass.getpass=bad\nsys.argv=['helper','/synthetic/node','/synthetic/approval']\ntry: runpy.run_path(sys.argv_path,run_name='__main__')\nexcept getpass.GetPassWarning: print('hidden input refused')";const output=execFileSync('python3',['-c','import sys;sys.argv_path='+JSON.stringify(helper)+'\n'+code],{encoding:'utf8'});assert.equal(output.trim(),'hidden input refused');});
test('emergency stop permits source drift but normal operations refuse it',t=>{const h=setup(t),old=h.a.sourceSha256;assert.equal(validateExecutionApproval(h.a,'stop',Date.now(),'b'.repeat(64)),old);assert.throws(()=>validateExecutionApproval(h.a,'preflight',Date.now(),'b'.repeat(64)));});
test('source drift suppresses OFF deploy but cannot block grant/key cleanup',async t=>{const h=setup(t);h.setKey(true);const a={...h.a,sourceSha256:'b'.repeat(64)};const io=createAdapter(a,'b'.repeat(64),{command:async(file,args)=>{if(args.includes('d1'))return {stdout:JSON.stringify([{success:true,meta:{changes:1}}])};if(args.includes('deployments'))return {stdout:JSON.stringify([{created_on:'now',versions:[{version_id:'v',percentage:100}]}])};if(args.includes('versions'))return {stdout:JSON.stringify({resources:{bindings:[{name:'DB',id:CONTRACT.database}]}})};throw Error('unexpected deployment');}});const r=await io.cleanup('operator_stop');assert.equal(r.grantStopped,true);assert.equal(r.keyAbsent,true);assert.equal(r.flagsOff,false);});
test('expired or ownerless key handoff cannot write a secret',async t=>{const h=setup(t);t.mock.timers.enable({apis:['Date'],now:h.a.endsAt});await assert.rejects(()=>h.io.installKey('sk-synthetic-only-key'),/window/);assert.ok(!h.calls.some(c=>c.args.includes('put')));});
test('key install requires both live shutdown owners',async t=>{const h=setup(t);h.dead();await assert.rejects(()=>h.io.installKey('sk-synthetic-only-key'));assert.ok(!h.calls.some(c=>c.args.includes('put')));});
test('production routes/build hooks/extra resources rejected offline',t=>{const h=setup(t),base=JSON.parse(readFileSync(h.a.configPath));for(const patch of [{routes:[{pattern:'edenmish.com',custom_domain:true}]},{build:{command:'arbitrary'}},{account_id:'different'},{services:[{binding:'OTHER',service:'production'}]},{workers_dev:true},{ai:{binding:'OTHER'}}])assert.throws(()=>verifyDeploymentSurface({...base,...patch}));});
function activationSetup(t){const h=setup(t);t.mock.timers.enable({apis:['Date'],now:h.a.startsAt});for(const [i,kind] of ['primary','watchdog'].entries())writeFileSync(join(h.dir,kind+'.json'),JSON.stringify({kind,at:Date.now(),endsAt:h.a.endsAt,pid:90000+i,sourceSha256:h.a.sourceSha256,grantId:CONTRACT.grantId}),{mode:0o600});writeFileSync(h.a.browserReceiptPath,JSON.stringify({verified:true,sender:CONTRACT.sender,incoming:'https://ops-staging.edenmish.com/webhooks/twilio/booking',method:'POST',fallback:'',endsAt:h.a.endsAt,verifiedAt:Date.now()}),{mode:0o600});h.setKey(true);return h;}
test('mocked activation verifies fresh grant and supervisors after deployment',async t=>{const h=activationSetup(t);assert.equal((await h.io.activate()).activeVerified,true);});
test('grant stop during deployment prevents START and triggers cleanup',async t=>{const h=activationSetup(t);h.setAfterDeploy(()=>h.stop());await assert.rejects(()=>h.io.activate(),/activation_unconfirmed/);assert.ok(h.calls.some(c=>c.args.includes('delete')));});
test('dead supervisor during deployment prevents START and triggers cleanup',async t=>{const h=activationSetup(t);h.setAfterDeploy(()=>h.dead());await assert.rejects(()=>h.io.activate(),/activation_unconfirmed/);assert.ok(h.calls.some(c=>c.args.includes('delete')));});

test('final grant read crossing expiry never reports START',async t=>{const h=activationSetup(t);h.setAfterFinalRead(()=>t.mock.timers.setTime(h.a.endsAt));await assert.rejects(()=>h.io.activate(),/activation_unconfirmed/);assert.ok(h.calls.some(c=>c.args.includes('delete')));});
