const escapeScript = (value) => JSON.stringify(String(value || '')).replace(/</g, '\\u003c');

export function businessAccountHtml(storefrontBase = 'https://edenmish.com') {
  const storefront = String(storefrontBase).replace(/\/+$/, '');
  return `<!doctype html>
<html lang="he" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#0F172A">
  <meta name="robots" content="noindex,nofollow">
  <title>EdenMish | החשבון העסקי שלי</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet">
  <style>
    :root{--navy:#0f172a;--navy-deep:#091121;--panel:rgba(21,30,50,.86);--panel-strong:#16213a;--purple:#5b2a86;--purple-bright:#8b5cf6;--lilac:#dfb7ff;--mint:#91d3c8;--mint-ink:#102822;--ink:#f8fafc;--muted:#a9b4c5;--line:rgba(223,183,255,.2);--line-soft:rgba(255,255,255,.08);--success:#8be0b0;--warning:#f6cf83;--danger:#fca5a5;--shadow:0 22px 70px rgba(0,0,0,.22)}
    *{box-sizing:border-box}html{background:var(--navy);color:var(--ink);font-family:"Hanken Grotesk",Arial,sans-serif;scroll-behavior:smooth}body{margin:0;min-height:100vh;background:radial-gradient(circle at 12% 6%,rgba(91,42,134,.3),transparent 34rem),radial-gradient(circle at 92% 88%,rgba(145,211,200,.1),transparent 30rem),var(--navy);overflow-x:hidden}a{color:inherit}button,input{font:inherit}.hidden{display:none!important}.muted{color:var(--muted)}.ltr{direction:ltr;unicode-bidi:embed}.material-symbols-outlined{font-variation-settings:"FILL" 0,"wght" 400,"GRAD" 0,"opsz" 24;line-height:1}
    :focus-visible{outline:3px solid rgba(145,211,200,.72);outline-offset:3px}.shell{width:min(1240px,100%);margin:auto;padding:18px 20px 72px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:22px}.identity{display:flex;align-items:center;gap:11px;min-width:0}.brand{font-size:1.45rem;font-weight:800;color:var(--lilac);text-decoration:none}.account-meta{display:flex;align-items:center;gap:9px;min-width:0}.avatar{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:var(--purple);border:1px solid rgba(223,183,255,.36);font-weight:800}.account-copy{min-width:0}.account-name{font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:250px}.account-role{color:var(--muted);font-size:.78rem}.top-actions{display:flex;gap:9px;align-items:center}
    button,.btn{border:0;border-radius:12px;min-height:44px;padding:10px 17px;font-weight:800;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:8px;transition:transform .16s ease,background .16s ease,border-color .16s ease}.btn:hover,button:hover{transform:translateY(-1px)}.primary{background:var(--mint);color:var(--mint-ink)}.purple{background:var(--purple);color:white}.ghost{background:rgba(255,255,255,.025);color:var(--lilac);border:1px solid var(--line)}button:disabled{opacity:.52;cursor:not-allowed;transform:none}
    .card{background:var(--panel);border:1px solid var(--line-soft);border-radius:20px;box-shadow:var(--shadow);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}h1,h2,h3,p{margin-top:0}h1{font-size:clamp(1.75rem,6vw,2.45rem);margin-bottom:8px}h2{font-size:1.23rem}h3{font-size:1rem}.section-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.section-title h2{margin:0}.section-link{color:var(--lilac);font-size:.86rem;text-decoration:none}.section-link:hover{text-decoration:underline}
    .auth{max-width:520px;margin:8vh auto;padding:28px}.auth .primary{width:100%}label{display:block;color:var(--muted);font-size:.88rem;margin:0 0 7px}.field{margin-bottom:15px}input{width:100%;border:1px solid rgba(223,183,255,.27);background:rgba(8,15,30,.72);color:white;border-radius:12px;min-height:48px;padding:12px 14px;outline:0}input:focus{border-color:var(--lilac);box-shadow:0 0 0 3px rgba(223,183,255,.12)}input[readonly]{color:var(--muted);cursor:not-allowed}.otp{display:flex;direction:ltr;gap:7px;justify-content:center;margin:18px 0}.otp input{width:48px;height:58px;text-align:center;font-size:1.45rem;font-weight:800;padding:0}.message{min-height:1.4em;color:var(--mint);margin-top:12px}.error{color:var(--danger)}
    .command-card{display:grid;grid-template-columns:minmax(300px,1.35fr) repeat(2,minmax(160px,.72fr)) minmax(170px,.72fr);align-items:stretch;overflow:hidden;margin-bottom:14px}.active-plan{display:grid;grid-template-columns:180px minmax(0,1fr);gap:16px;align-items:center;padding:16px;border-left:1px solid var(--line-soft)}.active-plan img{width:180px;height:auto;aspect-ratio:3/2;object-fit:cover;border-radius:15px;border:1px solid var(--line-soft);background:var(--navy-deep)}.active-copy{min-width:0}.eyebrow{color:var(--mint);font-size:.78rem;font-weight:700;margin-bottom:5px}.active-copy h1{font-size:1.34rem;margin-bottom:5px}.active-copy p{margin:0 0 9px;line-height:1.45}.active-meta{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.badge{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:5px 9px;font-size:.76rem;font-weight:700;border:1px solid var(--line);color:var(--lilac);background:rgba(91,42,134,.16)}.badge.active{color:#c9f5dd;border-color:rgba(139,224,176,.34);background:rgba(139,224,176,.1)}.stat{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:18px 15px;border-left:1px solid var(--line-soft)}.stat-icon{color:var(--lilac);font-size:29px;margin-bottom:7px}.stat-value{font-size:clamp(1.65rem,4vw,2.25rem);font-weight:800;line-height:1.1}.stat-value.mint{color:var(--mint)}.stat-label{font-size:.82rem;color:var(--muted);margin-top:5px;line-height:1.35}.command-action{display:flex;align-items:center;justify-content:center;padding:18px}.command-action .btn{width:100%;min-height:64px;font-size:1.04rem}
    .status-banner{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:14px;padding:14px 17px;margin-bottom:14px;border-radius:16px;border:1px solid var(--line);background:rgba(22,29,48,.94)}.status-banner.success{border-color:rgba(139,224,176,.6);background:rgba(33,84,66,.22)}.status-banner.pending{border-color:rgba(246,207,131,.45);background:rgba(107,77,22,.16)}.status-banner.problem{border-color:rgba(252,165,165,.52);background:rgba(116,38,38,.18)}.status-banner .status-icon{font-size:30px}.status-banner.success .status-icon{color:var(--success)}.status-banner.pending .status-icon{color:var(--warning)}.status-banner.problem .status-icon{color:var(--danger)}.status-copy b{display:block;margin-bottom:2px}.status-copy span{color:var(--muted);font-size:.86rem;line-height:1.45}.status-actions{display:flex;align-items:center;gap:8px}.icon-button{width:44px;padding:0;border-radius:50%}
    .operations{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.85fr);gap:14px;margin-bottom:14px}.feed{padding:20px;min-width:0}.list{display:grid;gap:0}.row{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:13px 0;border-bottom:1px solid var(--line-soft)}.row:last-child{border-bottom:0}.row-main{min-width:0}.route{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:610px;font-size:.87rem;margin-top:3px}.row-side{text-align:left;flex:0 0 auto}.row-side .muted{font-size:.78rem}.positive{color:var(--success)}.negative{color:#f9a8d4}.status-pill{display:inline-flex;border-radius:999px;padding:4px 8px;font-size:.72rem;font-weight:700;background:rgba(145,211,200,.1);color:var(--mint);margin-top:4px}.empty{text-align:center;padding:30px 18px;color:var(--muted)}.empty .material-symbols-outlined{font-size:42px;color:rgba(223,183,255,.5);display:block;margin-bottom:8px}.feed-toggle{width:100%;margin-top:8px;background:transparent;color:var(--lilac);border-top:1px solid var(--line-soft);border-radius:0;padding-top:14px}
    details.drawer{margin-bottom:11px;border:1px solid var(--line-soft);border-radius:18px;background:rgba(21,30,50,.78);overflow:hidden}details.drawer[open]{border-color:var(--line)}details.drawer>summary{list-style:none;cursor:pointer;min-height:76px;padding:16px 20px;display:flex;align-items:center;justify-content:space-between;gap:16px}details.drawer>summary::-webkit-details-marker{display:none}.summary-main{display:flex;align-items:center;gap:13px;min-width:0}.summary-icon{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;background:rgba(91,42,134,.42);color:var(--lilac);flex:0 0 auto}.summary-copy b{display:block}.summary-copy span{display:block;color:var(--muted);font-size:.83rem;margin-top:3px}.chevron{transition:transform .18s ease;color:var(--muted)}details[open] .chevron{transform:rotate(180deg)}.drawer-body{border-top:1px solid var(--line-soft);padding:20px}.program-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin:0 0 13px}.program-heading h3{font-size:1.08rem;margin:0}.program-heading p{margin:0;color:var(--muted);font-size:.82rem}.program-heading.spaced{margin-top:25px}
    .plans{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.plans.assisted{grid-template-columns:repeat(2,minmax(0,1fr))}.plan{position:relative;display:flex;flex-direction:column;overflow:hidden;border:1px solid var(--line-soft);border-radius:18px;background:rgba(8,15,30,.42)}.plan.current{border-color:rgba(145,211,200,.65)}.plan.recommended{border-color:rgba(223,183,255,.52)}.plan-art-wrap{position:relative}.plan-art{display:block;width:100%;height:auto;aspect-ratio:3/2;object-fit:cover;background:var(--navy-deep)}.plan-tag{position:absolute;top:10px;right:10px;border-radius:999px;padding:5px 9px;font-size:.72rem;font-weight:800;background:rgba(9,17,33,.88);border:1px solid var(--line);color:var(--lilac)}.plan-tag.active{color:#c9f5dd;border-color:rgba(139,224,176,.5)}.plan-body{padding:15px;display:flex;flex-direction:column;gap:11px;flex:1}.plan-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.plan-name{font-size:1.18rem;font-weight:800}.plan-kind{font-size:.75rem;color:var(--mint);margin-bottom:3px}.plan-price{font-size:1.55rem;font-weight:800;color:var(--lilac);white-space:nowrap}.best-for{color:var(--muted);line-height:1.5;font-size:.86rem;margin:0}.saving-box{background:rgba(145,211,200,.08);border:1px solid rgba(145,211,200,.22);border-radius:12px;padding:10px}.saving-value{color:var(--mint);font-weight:800}.saving-label{color:#c7f3ec;font-size:.75rem;margin-top:2px}.breakdown{display:grid;gap:7px;border-top:1px solid var(--line-soft);padding-top:11px}.breakdown-row{display:flex;justify-content:space-between;gap:10px;font-size:.8rem}.breakdown-row span{color:var(--muted)}.rate-before{text-decoration:line-through}.benefits{margin:0;padding:0 18px 0 0;color:#dce6f5;display:grid;gap:6px;font-size:.82rem;line-height:1.42}.plan .topup,.plan .assist{width:100%;margin-top:auto}.fine-print{margin:15px 1px 0;color:var(--muted);font-size:.76rem;line-height:1.55}
    .profile-grid{display:grid;grid-template-columns:1fr 1fr 1fr 1fr auto;gap:11px;align-items:end}.profile-message{margin-top:10px}.settings-note{color:var(--muted);font-size:.82rem;margin:0 0 16px;line-height:1.5}
    @media(max-width:1040px){.command-card{grid-template-columns:1.35fr repeat(2,.65fr)}.command-action{grid-column:1/-1;border-top:1px solid var(--line-soft)}.command-action .btn{min-height:52px}.plans{grid-template-columns:1fr 1fr}.plans .plan:last-child{grid-column:1/-1;max-width:470px;width:100%;justify-self:center}.profile-grid{grid-template-columns:1fr 1fr}.profile-grid button{align-self:end}}
    @media(max-width:820px){.operations{grid-template-columns:1fr}.command-card{grid-template-columns:1fr 1fr}.active-plan{grid-column:1/-1;border-left:0;border-bottom:1px solid var(--line-soft)}.stat:nth-of-type(2){border-left:0}.command-action{grid-column:1/-1}.top{align-items:flex-start}.account-meta{display:none}}
    @media(max-width:620px){.shell{padding:14px 14px 52px}.top{margin-bottom:14px}.top-actions{gap:6px}.top-actions .btn,.top-actions button{padding:9px 11px}.top-actions .label{display:none}.command-card{grid-template-columns:1fr 1fr}.active-plan{grid-template-columns:112px minmax(0,1fr);padding:13px;gap:12px}.active-plan img{width:112px}.active-copy h1{font-size:1.06rem}.active-copy p{font-size:.78rem}.stat{padding:14px 8px}.stat-value{font-size:1.65rem}.stat-label{font-size:.75rem}.status-banner{grid-template-columns:auto 1fr;padding:13px}.status-actions{grid-column:1/-1;width:100%}.status-actions .btn{flex:1}.operations{gap:11px}.feed{padding:16px}.row{align-items:flex-start}.route{max-width:205px}.drawer-body{padding:14px}.plans,.plans.assisted{grid-template-columns:1fr}.plans .plan:last-child{grid-column:auto;max-width:none}.program-heading{display:block}.program-heading p{margin-top:4px}.profile-grid{grid-template-columns:1fr}.otp input{width:42px;height:54px}.summary-copy span{max-width:230px}.drawer>summary{padding:14px}.avatar{width:38px;height:38px}.brand{font-size:1.25rem}}
    @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.btn,button,.chevron{transition:none}}
  </style>
</head>
<body>
<main class="shell">
  <header class="top">
    <div class="identity"><a class="brand" href="${storefront}">EdenMish</a><div id="account-meta" class="account-meta hidden"><div id="avatar" class="avatar">EM</div><div class="account-copy"><div id="header-company" class="account-name">החשבון העסקי</div><div id="header-role" class="account-role">חשבון מאומת</div></div></div></div>
    <div class="top-actions"><a id="header-new-delivery" class="btn primary hidden" href="${storefront}/booking.html?business=1" aria-label="משלוח חדש"><span class="material-symbols-outlined" aria-hidden="true">add</span><span class="label">משלוח חדש</span></a><button id="logout" class="ghost hidden" aria-label="יציאה"><span class="material-symbols-outlined" aria-hidden="true">logout</span><span class="label">יציאה</span></button></div>
  </header>

  <section id="auth" class="auth card">
    <div id="email-step">
      <h1>החשבון העסקי שלך</h1><p class="muted">נשלח אליך קישור כניסה מהיר וגם קוד בן 6 ספרות. אין צורך בסיסמה.</p>
      <form id="email-form"><div class="field"><label for="email">אימייל עסקי</label><input id="email" type="email" dir="ltr" autocomplete="email" required placeholder="name@business.co.il"></div><button class="purple" type="submit">שלחו לי קישור וקוד</button></form>
    </div>
    <div id="code-step" class="hidden">
      <h1>בדקו את האימייל</h1><p class="muted">אפשר ללחוץ על הקישור שקיבלתם או להזין כאן את הקוד.</p>
      <form id="code-form"><div class="otp" aria-label="קוד אימות בן שש ספרות">${Array.from({ length: 6 }, (_, i) => `<input inputmode="numeric" pattern="[0-9]*" maxlength="1" autocomplete="${i === 0 ? 'one-time-code' : 'off'}" aria-label="ספרה ${i + 1}">`).join('')}</div><button class="purple" type="submit">כניסה לחשבון</button></form>
      <button id="back-email" class="ghost" type="button">שינוי אימייל</button>
    </div>
    <div id="auth-message" class="message" aria-live="polite"></div>
  </section>

  <section id="dashboard" class="hidden">
    <section class="command-card card" aria-labelledby="active-plan-title">
      <div class="active-plan"><img id="active-plan-art" src="${storefront}/assets/business-wallet.webp" alt="ארנק דיגיטלי מחבר רשת של שליחים על אופנועים" width="1200" height="800"><div class="active-copy"><div id="active-plan-eyebrow" class="eyebrow">החשבון העסקי שלך</div><h1 id="active-plan-title">עדיין אין מסלול פעיל</h1><p id="active-plan-copy" class="muted">בחרו תוכנית כדי להפעיל מחיר עסקי ויתרה למשלוחים.</p><div class="active-meta"><span id="active-plan-badge" class="badge">ממתין לבחירה</span><a id="active-plan-link" class="section-link" href="#programs">לכל התוכניות</a></div></div></div>
      <div class="stat"><span class="material-symbols-outlined stat-icon" aria-hidden="true">account_balance_wallet</span><div class="stat-value mint"><bdi id="balance">0</bdi> ₪</div><div class="stat-label">יתרה זמינה<br><span id="reserved">0 ₪ בהמתנה</span></div></div>
      <div class="stat"><span class="material-symbols-outlined stat-icon" aria-hidden="true">local_shipping</span><div id="estimated-deliveries" class="stat-value">—</div><div id="estimate-basis" class="stat-label">משלוחים משוערים</div></div>
      <div class="command-action"><a id="primary-action" class="btn primary" href="#programs"><span class="material-symbols-outlined" aria-hidden="true">add</span><span id="primary-action-label">בחירת תוכנית</span></a></div>
    </section>

    <section id="topup-status" class="status-banner hidden" aria-live="polite" role="status"><span id="topup-status-icon" class="material-symbols-outlined status-icon" aria-hidden="true">schedule</span><div class="status-copy"><b id="topup-status-title"></b><span id="topup-status-copy"></span></div><div id="topup-status-actions" class="status-actions"></div></section>
    <div id="payment-message" class="message" aria-live="assertive"></div>

    <div class="operations">
      <article class="feed card"><div class="section-title"><h2>משלוחים אחרונים</h2><a class="section-link" href="${storefront}/booking.html?business=1">יצירת משלוח</a></div><div id="orders" class="list"></div><button id="orders-toggle" class="feed-toggle hidden" type="button"></button></article>
      <article class="feed card"><div class="section-title"><h2>פעילות בארנק</h2><span id="expiry" class="muted"></span></div><div id="entries" class="list"></div><button id="entries-toggle" class="feed-toggle hidden" type="button"></button></article>
    </div>

    <details id="programs" class="drawer">
      <summary><span class="summary-main"><span class="summary-icon"><span class="material-symbols-outlined" aria-hidden="true">tune</span></span><span class="summary-copy"><b>השוואה ושינוי תוכנית</b><span>חבילת ניסיון, ארנק עסקי ומסלולי Silver, Gold ו־Platinum</span></span></span><span class="material-symbols-outlined chevron" aria-hidden="true">expand_more</span></summary>
      <div class="drawer-body">
        <div class="program-heading"><div><h3>תוכניות בליווי אישי</h3><p>מתחילים או מתאימים חבילה יחד עם עדן, ללא תשלום עצמי מהחשבון.</p></div></div>
        <div id="assisted-programs" class="plans assisted"></div>
        <div class="program-heading spaced"><div><h3>מסלולי חשבון וטעינת יתרה</h3><p>תשלום מאובטח דרך Shopify, מחיר עסקי אוטומטי ויתרה בזמן אמת.</p></div></div>
        <div id="plan-cards" class="plans"></div>
        <p class="fine-print">החיסכון מחושב מול מחיר הבסיס הרגיל למשלוח קטן בשעות הפעילות, לפי המחירון הנוכחי. תוספות גודל, ערב וסוף שבוע מחושבות בנפרד. הקרדיט מחויב לפי השימוש בפועל.</p>
      </div>
    </details>

    <details id="business-details" class="drawer">
      <summary><span class="summary-main"><span class="summary-icon"><span class="material-symbols-outlined" aria-hidden="true">domain</span></span><span class="summary-copy"><b>פרטי העסק</b><span id="business-summary">שם העסק, איש קשר וטלפון</span></span></span><span class="material-symbols-outlined chevron" aria-hidden="true">expand_more</span></summary>
      <div class="drawer-body"><p class="settings-note">האימייל משמש לכניסה המאובטחת לחשבון ולכן אינו ניתן לשינוי כאן.</p><form id="profile-form" class="profile-grid"><div><label for="company">שם העסק</label><input id="company" autocomplete="organization"></div><div><label for="contact-name">שם איש קשר</label><input id="contact-name" autocomplete="name"></div><div><label for="phone">טלפון</label><input id="phone" dir="ltr" autocomplete="tel"></div><div><label for="login-email">אימייל כניסה</label><input id="login-email" dir="ltr" type="email" readonly aria-readonly="true"></div><button class="ghost" type="submit">שמירה</button></form><div id="profile-message" class="message profile-message" aria-live="polite"></div></div>
    </details>
  </section>
</main>
<script>
const STOREFRONT=${escapeScript(storefront)};
const WHATSAPP='https://wa.me/972534058498';
const $=id=>document.getElementById(id);
const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('he-IL',{maximumFractionDigits:2}).format(Number(n||0));
const date=n=>n?new Intl.DateTimeFormat('he-IL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(Number(n))):'—';
const planNames={silver:'Silver · כסף',gold:'Gold · זהב',platinum:'Platinum · פלטינום'};
const planAlt={silver:'שליח על אופנוע מחבר ארבע נקודות שירות במסלול עירוני',gold:'שליח על אופנוע נכנס למסלול עדיפות המחבר שני אזורי שירות',platinum:'שליח על אופנוע נוסע אל מרכז שליטה המחבר שלושה אזורי שירות'};
const orderStatuses={delivered:'נמסר',paid:'שולם',to_pickup:'בדרך לאיסוף',picked_up:'נאסף',to_dropoff:'בדרך ליעד',cancelled:'בוטל',wallet_reserved:'שמור בארנק',pending:'ממתין'};
const assistedPrograms=[
  {id:'trial',name:'חבילת ניסיון',kind:'בהזמנה אישית',amount:150,art:'business-trial.webp',alt:'שליח על אופנוע מתחיל מסלול משלוח באזור עירוני',copy:'להתחיל בלי התחייבות ולבדוק את השירות עם 5 משלוחים חסכוניים.',benefits:['5 משלוחים חסכוניים באזור 1','מימוש בתוך 14 יום','ליווי אישי ישירות מול עדן']},
  {id:'wallet',name:'ארנק עסקי',kind:'תוכנית בליווי אישי',amount:1500,art:'business-wallet.webp',alt:'ארנק דיגיטלי מחבר רשת של שליחים על אופנועים',copy:'יתרה חודשית לעסק עם משלוחים קבועים באזור 1 וקשר ישיר.',benefits:['עד 50 משלוחים חסכוניים באזור 1','יתרה תקפה ל־30 יום','התאמה ואישור ישירות מול עדן']}
];
let challenge=null,snapshot=null,firstRender=true,ordersExpanded=false,entriesExpanded=false,pollTimer=null;

async function api(path,options={}){const response=await fetch(path,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||'request_failed');error.status=response.status;error.data=data;throw error}return data}
function authMessage(text,error=false){const el=$('auth-message');el.textContent=text||'';el.classList.toggle('error',error)}
function showAuth(){ $('auth').classList.remove('hidden');$('dashboard').classList.add('hidden');$('logout').classList.add('hidden');$('header-new-delivery').classList.add('hidden');$('account-meta').classList.add('hidden') }
function showDashboard(){ $('auth').classList.add('hidden');$('dashboard').classList.remove('hidden');$('logout').classList.remove('hidden');$('header-new-delivery').classList.remove('hidden');$('account-meta').classList.remove('hidden') }
function planArt(id){return STOREFRONT+'/assets/business-'+(planNames[id]?id:'wallet')+'.webp'}
function initials(value){const words=String(value||'EM').trim().split(/\\s+/).filter(Boolean);return words.slice(0,2).map(w=>w[0]).join('').toUpperCase()||'EM'}
function activeTopupId(){return sessionStorage.getItem('edenmish_active_topup')||''}
function dismissTopup(id){if(id)sessionStorage.setItem('edenmish_dismissed_topup',id);sessionStorage.removeItem('edenmish_active_topup');$('topup-status').classList.add('hidden');stopPolling()}
function relevantTopup(){if(!snapshot||!snapshot.topups)return null;const active=activeTopupId();const dismissed=sessionStorage.getItem('edenmish_dismissed_topup')||'';if(active){const match=snapshot.topups.find(t=>t.id===active);if(match)return match}const recent=snapshot.topups.find(t=>t.status==='checkout_ready'&&Date.now()-Number(t.created_at)<86400000&&t.id!==dismissed);return recent||null}
function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
function updatePolling(topup){stopPolling();if(topup&&(topup.status==='created'||topup.status==='checkout_ready'))pollTimer=setInterval(()=>{if(document.visibilityState==='visible')refreshSnapshot(true)},6000)}
function renderTopupStatus(){const banner=$('topup-status');const topup=relevantTopup();if(!topup){banner.className='status-banner hidden';stopPolling();return}const plan=planNames[topup.plan_id]||topup.plan_id;let tone='pending',icon='schedule',title='התשלום ממתין להשלמה',copy='התשלום נפתח ב־Shopify בלשונית נפרדת. אם כבר שילמתם, אל תשלמו שוב — היתרה תתעדכן כאן אוטומטית.',actions='';if(topup.status==='paid'){tone='success';icon='check_circle';title='הטעינה הושלמה';copy='נוספו ₪'+money(topup.amount)+' ליתרה ומסלול '+plan+' פעיל כעת.'}else if(topup.status==='mismatch'){tone='problem';icon='error';title='התשלום התקבל ונדרש אימות';copy='אל תשלמו שוב. התשלום נמצא בבדיקה ואנחנו נטפל בהתאמת היתרה.'}else if(topup.checkout_url){actions='<a class="btn ghost" href="'+esc(topup.checkout_url)+'" target="_blank" rel="noopener">חזרה לתשלום</a>'}banner.className='status-banner '+tone;$('topup-status-icon').textContent=icon;$('topup-status-title').textContent=title;$('topup-status-copy').textContent=copy;$('topup-status-actions').innerHTML=actions+'<button class="icon-button ghost" type="button" aria-label="סגירת ההודעה" data-dismiss-topup="'+esc(topup.id)+'"><span class="material-symbols-outlined" aria-hidden="true">close</span></button>';const close=banner.querySelector('[data-dismiss-topup]');if(close)close.onclick=()=>dismissTopup(topup.id);updatePolling(topup)}
function renderAssistedPrograms(){$('assisted-programs').innerHTML=assistedPrograms.map(program=>'<article class="plan"><div class="plan-art-wrap"><img class="plan-art" src="'+STOREFRONT+'/assets/'+esc(program.art)+'" alt="'+esc(program.alt)+'" width="1200" height="800" loading="lazy"><span class="plan-tag">'+esc(program.kind)+'</span></div><div class="plan-body"><div class="plan-head"><div><div class="plan-kind">תוכנית בליווי אישי</div><div class="plan-name">'+esc(program.name)+'</div></div><div class="plan-price">₪'+money(program.amount)+'</div></div><p class="best-for">'+esc(program.copy)+'</p><ul class="benefits">'+program.benefits.map(item=>'<li>'+esc(item)+'</li>').join('')+'</ul><button class="ghost assist" type="button" data-assist="'+esc(program.id)+'">בדיקת התאמה עם עדן</button></div></article>').join('');document.querySelectorAll('[data-assist]').forEach(button=>button.onclick=()=>openAssistedProgram(button.dataset.assist))}
function openAssistedProgram(id){const program=assistedPrograms.find(item=>item.id===id);if(!program)return;const text='שלום עדן, אשמח לבדוק התאמה לתוכנית '+program.name+' לעסק שלי.';window.open(WHATSAPP+'?text='+encodeURIComponent(text),'_blank','noopener')}
function renderPlans(){const s=snapshot;$('plan-cards').innerHTML=s.plans.map(plan=>{const value=plan.value||{},example=value.example||{},current=s.account.plan_id===plan.id;return '<article class="plan '+(current?'current ':'')+(value.recommended?'recommended':'')+'"><div class="plan-art-wrap"><img class="plan-art" src="'+planArt(plan.id)+'" alt="'+esc(planAlt[plan.id]||'מסלול משלוחים עסקי')+'" width="1200" height="800" loading="lazy">'+(current?'<span class="plan-tag active">מסלול פעיל</span>':value.recommended?'<span class="plan-tag">הבחירה המומלצת</span>':'')+'</div><div class="plan-body"><div class="plan-head"><div><div class="plan-kind">טעינה עצמית בחשבון</div><div class="plan-name">'+esc(planNames[plan.id]||plan.name_he)+'</div></div><div class="plan-price">₪'+money(plan.amount)+'</div></div><p class="best-for">'+esc(value.best_for||'מסלול עסקי גמיש')+'</p><div class="saving-box"><div class="saving-value">חיסכון מוערך ₪'+money(example.estimated_savings)+'</div><div class="saving-label">במחזור הקרדיט הזה · עד '+money(value.max_discount_percent)+'% למשלוח</div></div><div class="breakdown"><div class="breakdown-row"><span>דוגמה: '+esc(example.service_he||'רגיל')+' · אזור '+money(example.zone)+'</span><b><span class="rate-before">₪'+money(example.public_rate)+'</span> ← ₪'+money(example.member_rate)+'</b></div><div class="breakdown-row"><span>משלוחים משוערים</span><b>כ־'+money(example.deliveries)+'</b></div></div><ul class="benefits">'+(value.benefits||[]).map(item=>'<li>'+esc(item)+'</li>').join('')+'</ul><button class="purple topup" type="button" data-plan="'+esc(plan.id)+'">'+(current?'טעינה נוספת במסלול':'בחירת '+esc(plan.name_he)+' וטעינה')+'</button></div></article>'}).join('');document.querySelectorAll('.topup').forEach(button=>button.onclick=()=>topup(button))}
function renderOrders(){const list=snapshot.orders||[],visible=ordersExpanded?list:list.slice(0,5);$('orders').innerHTML=visible.length?visible.map(order=>'<div class="row"><div class="row-main"><b>משלוח #'+esc(order.id)+'</b><div class="route muted">'+esc(order.pickup||'—')+' ← '+esc(order.dropoff||'—')+'</div></div><div class="row-side"><b><bdi>₪'+money(order.price)+'</bdi></b><div><span class="status-pill">'+esc(orderStatuses[order.status]||orderStatuses[order.payment_status]||order.status||order.payment_status||'בטיפול')+'</span></div></div></div>').join(''):'<div class="empty"><span class="material-symbols-outlined" aria-hidden="true">two_wheeler</span>עדיין אין משלוחים בחשבון.</div>';const toggle=$('orders-toggle');toggle.classList.toggle('hidden',list.length<=5);toggle.textContent=ordersExpanded?'הצגת חמשת האחרונים':'הצגת כל '+list.length+' המשלוחים'}
function renderEntries(){const labels={topup:'טעינת יתרה',reserve:'שמירת יתרה למשלוח',capture:'חיוב משלוח',release:'שחרור יתרה',refund:'זיכוי',expiry:'פקיעת יתרה',adjustment:'התאמה'};const list=snapshot.entries||[],visible=entriesExpanded?list:list.slice(0,5);$('entries').innerHTML=visible.length?visible.map(entry=>{const delta=Number(entry.available_delta||0);return '<div class="row"><div class="row-main"><b>'+esc(labels[entry.entry_type]||entry.entry_type)+'</b><div class="muted">'+date(entry.created_at)+(entry.order_id?' · משלוח #'+esc(entry.order_id):'')+'</div></div><b class="ltr '+(delta>0?'positive':delta<0?'negative':'')+'">'+(delta>0?'+':'')+money(delta)+' ₪</b></div>'}).join(''):'<div class="empty"><span class="material-symbols-outlined" aria-hidden="true">account_balance_wallet</span>פעילות היתרה תופיע כאן.</div>';const toggle=$('entries-toggle');toggle.classList.toggle('hidden',list.length<=5);toggle.textContent=entriesExpanded?'הצגת חמש הפעולות האחרונות':'הצגת כל '+list.length+' הפעולות'}
function render(){const s=snapshot,estimate=s.wallet.delivery_estimate,plan=s.plans.find(item=>item.id===s.account.plan_id),hasPlan=Boolean(plan);$('balance').textContent=money(s.wallet.available);$('reserved').textContent=money(s.wallet.reserved)+' ₪ בהמתנה';$('estimated-deliveries').textContent=estimate?money(estimate.count):'—';$('estimate-basis').textContent=estimate?'משלוחים משוערים · '+estimate.service_he+' באזור '+money(estimate.zone):'לאחר בחירת מסלול תוצג הערכה';$('expiry').textContent=s.wallet.next_expiry?'₪'+money(s.wallet.next_expiry.amount)+' עד '+date(s.wallet.next_expiry.at):'אין יתרה שעומדת לפוג';const displayName=s.account.company_name||s.user.name||s.user.email;$('header-company').textContent=displayName;$('header-role').textContent=s.user.role==='owner'?'בעלים · חשבון מאומת':'חשבון מאומת';$('avatar').textContent=initials(displayName);$('active-plan-art').src=hasPlan?planArt(plan.id):STOREFRONT+'/assets/business-wallet.webp';$('active-plan-art').alt=hasPlan?(planAlt[plan.id]||'מסלול משלוחים עסקי'):'ארנק דיגיטלי מחבר רשת של שליחים על אופנועים';$('active-plan-eyebrow').textContent=hasPlan?'המסלול הפעיל':'החשבון העסקי שלך';$('active-plan-title').textContent=hasPlan?(planNames[plan.id]||plan.name_he):'עדיין אין מסלול פעיל';$('active-plan-copy').textContent=hasPlan?plan.value.best_for:'בחרו אחת מחמש התוכניות כדי להתחיל.';$('active-plan-badge').textContent=hasPlan?'פעיל · אזורים '+plan.zones.join('–'):'ממתין לבחירה';$('active-plan-badge').className='badge '+(hasPlan?'active':'');$('primary-action').href=hasPlan?STOREFRONT+'/booking.html?business=1':'#programs';$('primary-action-label').textContent=hasPlan?'משלוח חדש':'בחירת תוכנית';$('header-new-delivery').href=hasPlan?STOREFRONT+'/booking.html?business=1':'#programs';$('company').value=s.account.company_name||'';$('contact-name').value=s.user.name||'';$('phone').value=s.user.phone||'';$('login-email').value=s.user.email||'';$('business-summary').textContent=(s.account.company_name||'שם העסק לא הוגדר')+' · '+(s.user.name||'איש קשר לא הוגדר');renderAssistedPrograms();renderPlans();renderOrders();renderEntries();renderTopupStatus();if(firstRender){$('programs').open=!hasPlan;firstRender=false}}
async function refreshSnapshot(silent=false){try{snapshot=await api('/api/business/me');render();showDashboard()}catch(error){if(error.status===401)showAuth();else if(!silent){$('payment-message').textContent='לא הצלחנו לרענן את החשבון כרגע.';$('payment-message').classList.add('error')}}}
async function topup(button){const plan=button.dataset.plan,original=button.textContent,checkoutWindow=window.open('about:blank','_blank');button.disabled=true;button.textContent='מכין תשלום…';$('payment-message').textContent='';try{const data=await api('/api/business/topups',{method:'POST',body:JSON.stringify({plan_id:plan})});if(!data.checkout_url)throw new Error('checkout_unavailable');sessionStorage.setItem('edenmish_active_topup',data.topup_id);sessionStorage.removeItem('edenmish_dismissed_topup');if(checkoutWindow){checkoutWindow.opener=null;checkoutWindow.location.replace(data.checkout_url)}else location.assign(data.checkout_url);await refreshSnapshot(true)}catch(error){if(checkoutWindow)checkoutWindow.close();$('payment-message').textContent='לא הצלחנו לפתוח את התשלום. לא חויבתם — נסו שוב או פנו לעדן.';$('payment-message').classList.add('error');button.disabled=false;button.textContent=original}}
$('orders-toggle').onclick=()=>{ordersExpanded=!ordersExpanded;renderOrders()};$('entries-toggle').onclick=()=>{entriesExpanded=!entriesExpanded;renderEntries()};
$('email-form').onsubmit=async event=>{event.preventDefault();authMessage('שולחים…');const button=event.submitter;button.disabled=true;try{const data=await api('/api/business/auth/request',{method:'POST',body:JSON.stringify({email:$('email').value})});challenge=data.challenge;$('email-step').classList.add('hidden');$('code-step').classList.remove('hidden');authMessage('שלחנו קישור וקוד לאימייל.');document.querySelector('.otp input').focus()}catch(error){authMessage(error.status===429?'נשלחו יותר מדי בקשות. נסו שוב מאוחר יותר.':'לא הצלחנו לשלוח. בדקו את האימייל ונסו שוב.',true)}finally{button.disabled=false}};
$('code-form').onsubmit=async event=>{event.preventDefault();const code=[...document.querySelectorAll('.otp input')].map(input=>input.value).join('');if(code.length!==6)return authMessage('נא להזין את כל שש הספרות.',true);try{await api('/api/business/auth/verify',{method:'POST',body:JSON.stringify({challenge,code})});history.replaceState({},'',location.pathname);await refreshSnapshot()}catch(error){authMessage(error.message==='expired'?'פג תוקף הקוד. בקשו קוד חדש.':'הקוד אינו נכון.',true)}};
document.querySelectorAll('.otp input').forEach((input,index,all)=>{input.oninput=()=>{input.value=input.value.replace(/\\D/g,'').slice(-1);if(input.value&&all[index+1])all[index+1].focus()};input.onkeydown=event=>{if(event.key==='Backspace'&&!input.value&&all[index-1])all[index-1].focus()};input.onpaste=event=>{const digits=(event.clipboardData.getData('text')||'').replace(/\\D/g,'').slice(0,6);if(digits){event.preventDefault();digits.split('').forEach((digit,digitIndex)=>{if(all[digitIndex])all[digitIndex].value=digit});if(all[Math.min(digits.length,5)])all[Math.min(digits.length,5)].focus()}}});
$('back-email').onclick=()=>{$('code-step').classList.add('hidden');$('email-step').classList.remove('hidden');authMessage('')};
$('logout').onclick=async()=>{await api('/api/business/logout',{method:'POST',body:'{}'}).catch(()=>{});sessionStorage.removeItem('edenmish_active_topup');location.reload()};
$('profile-form').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$('profile-message').textContent='שומרים…';$('profile-message').classList.remove('error');try{await api('/api/business/profile',{method:'PUT',body:JSON.stringify({company_name:$('company').value,name:$('contact-name').value,phone:$('phone').value})});$('profile-message').textContent='הפרטים נשמרו.';await refreshSnapshot(true)}catch(error){$('profile-message').textContent='לא הצלחנו לשמור כרגע.';$('profile-message').classList.add('error')}finally{button.disabled=false}};
window.addEventListener('focus',()=>{if(snapshot)refreshSnapshot(true)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&snapshot)refreshSnapshot(true)});
(async()=>{const query=new URLSearchParams(location.search);if(query.get('challenge')&&query.get('token')){try{await api('/api/business/auth/verify',{method:'POST',body:JSON.stringify({challenge:query.get('challenge'),token:query.get('token')})})}catch(error){authMessage(error.message==='expired'?'הקישור פג. בקשו קישור חדש.':'הקישור אינו תקין.',true)}finally{history.replaceState({},'',location.pathname)}}await refreshSnapshot()})();
</script>
</body></html>`;
}
